<a href="https://colab.research.google.com/github/mkhatu1/nlp/blob/main/EBTsentTokenz.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Updated: 10/13/20

#need to stem data

In [ ]:
# Python program to generate word vectors using Word2Vec 
# importing all necessary modules 
from nltk.tokenize import sent_tokenize, word_tokenize 
import warnings 
warnings.filterwarnings(action = 'ignore') 
import nltk
nltk.download('punkt')
import gensim
from gensim.models import Word2Vec 

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


In [ ]:
from gensim.parsing.preprocessing import strip_non_alphanum, split_alphanum
from gensim.parsing.preprocessing import strip_numeric
from gensim.parsing.preprocessing import remove_stopwords
from gensim.parsing.preprocessing import STOPWORDS
from gensim.parsing.porter import PorterStemmer as p
from gensim.parsing.preprocessing import strip_multiple_whitespaces

In [ ]:
#  Reads ‘Requirements.txt’ file 
rq = open("drive/My Drive/Datasets/EBT/Requirements.txt", "r") 
rq = rq.read() 
# r = p.stem(rq) 

In [ ]:
# l = [i for i in rq.readlines()]

In [ ]:
a = [] 
other_words = STOPWORDS.union(['shall' ] ) 
# other_words = ['shall']

# iterate through each sentence in the file 
for i in sent_tokenize(rq): 
    t = [] 
      
    # tokenize the sentence into words 
    for j in word_tokenize(i):
      if not j.lower() in other_words:
            j= strip_non_alphanum(j)
            j= strip_numeric(j)
            j= strip_multiple_whitespaces(j)
            # j = [j if j.lower()!='']
            print('j-----------', j)
        # j= remove_stopwords(j)
        #print(j + ' --> ' + p.stem(j))
        # if not j.lower() in other_words:
            #t.append(j.lower()) 
      
    a.append(t) 

In [ ]:
len(a)

37

In [ ]:
a #a is perfectly preprocessed RQ

#old preprocessing

In [ ]:
# Retrieve all of the vectors from a trained model as follows:
X = model[model.wv.vocab]

In [ ]:
# writing to file 
file1 = open('myfile.txt', 'w') 
file1.writelines(rq) 
file1.close() 

In [ ]:
# Using readlines() 
file1 = open('myfile.txt', 'r') 
# file1 = file1.read()
Lines = file1.readlines() 

In [ ]:
rq_list = []
count = 0
# Strips the newline character 
for line in Lines: 
  count+=1
  line = line.lower()
  line = strip_non_alphanum(line)
  line = strip_numeric(line)
  line = remove_stopwords(line)
  # line = p.stem_sentence(line)
  rq_list.append(line)
  print("Line{}: {}".format(count, line.strip())) 


In [ ]:
# # convert list to string
# rq = ' '.join(map(str, rq_list)) 
# rq

#Preprocess the Source Code file using gensim


In [ ]:
import csv
import re
ifile  = open('/content/drive/My Drive/Datasets/EBT/SourceCode.csv', "r")

t = []
b = []
scid = []
line = []
read = csv.reader(ifile)
for row in read :
    if (row[1] != ""):
        scid.append (row[0])
        lines = re.split("([A-Z][^A-Z]*)", row[1]) #= row[1].split()
        lines = [strip_non_alphanum(j) for j in lines ]
        lines = [strip_numeric(j) for j in lines ]
        lines = [strip_multiple_whitespaces(j) for j in lines ]
        lines = [ j for j in lines if len(j)>=3 ]
        lines = [j.lower() for j in lines]
        #print('l--------------', lines)
        b.append(lines)

        # for j in lines:
        # #   print('word-------------', j)
           
        #       if not j.lower() in other_words:
        #           j= strip_non_alphanum(j)           
        #           j= strip_numeric(j)
        #           j= strip_multiple_whitespaces(j)
        #           j= j.lower()

        #           print('w---------------', j)
        # #           #print(j)  
        #           t.append(j.lower()) 
        # b.append(t)
                                   
        #print ("wordssssssssssssssssssssssssssssssssssss", lines)


In [ ]:
list(b)

In [ ]:
all_doc = []
all_doc.extend(a)
all_doc.extend(b)

In [ ]:
all_doc

[['',
  'requirements',
  'managed',
  'rd',
  'party',
  'requirements',
  'management',
  'tool',
  'doors',
  ' '],
 ['',
  'non requirement',
  'artifacts',
  'managed',
  'rd',
  'party',
  'tools',
  'rational',
  'rose',
  'clear',
  'case',
  '',
  'registered',
  'subscribers',
  'allowed',
  'establish',
  'traces',
  ' '],
 ['', 'user', 'register', 'subscriber', ' '],
 ['',
  'registration',
  'subscriber',
  'register',
  'control',
  'subscriber',
  'manager',
  '',
  'user',
  'establish',
  'traces',
  'requirements',
  'types',
  'artifacts',
  'establishing',
  'subscription',
  'artifact',
  'relevant',
  'requirement',
  '',
  'artifact',
  'placed',
  'control',
  'subscriber',
  'manager',
  '',
  'user',
  'able',
  'delete',
  'subscriptions',
  ' '],
 ['',
  'subscriber',
  'manager',
  'register',
  'eventserver',
  'receive',
  'relevant',
  'event',
  'messages',
  ' '],
 ['',
  'subscriber',
  'manager',
  'online',
  ' ',
  'push',
  'model',
  'send',
  'e

In [ ]:
len(a)

37

In [ ]:
# Create Skip Gram model 
model = gensim.models.Word2Vec(all_doc, min_count = 1, size = 50, 
                                             window = 5, sg = 1) 

In [ ]:
l1 =list(model.wv.vocab)

In [ ]:
len(l1)

1705

In [ ]:
#model vector 
word_vectors = model.wv

#test similarity

In [ ]:
sim = []

In [ ]:
counti = 0
countj = 0
for i in a:
  counti += a.count(i)
  #print(i)
  for j in b:
  
    countj += b.count(j)
    similarity = word_vectors.wmdistance(i, j)
    sim.append("{:.4f}".format(similarity))
    #print("{:.4f}".format(similarity))
    print(counti, countj, sim)

In [ ]:
len(sim)

1850

In [ ]:
sim

['2.8519',
 '2.8519',
 '2.8519',
 '2.8519',
 '2.8519',
 '2.8519',
 '2.8519',
 '2.8519',
 '2.8519',
 '2.8519',
 '2.8519',
 '2.8519',
 '2.8519',
 '2.8519',
 '2.8519',
 '2.8519',
 '2.8519',
 '2.8519',
 '2.8519',
 '2.8519',
 '2.8519',
 '2.8519',
 '2.8519',
 '2.8519',
 '2.8519',
 '2.8519',
 '2.8519',
 '2.8519',
 '2.8519',
 '2.8519',
 '2.8519',
 '2.8519',
 '2.8519',
 '2.8519',
 '2.8519',
 '2.8519',
 '2.8519',
 '2.8519',
 '2.8519',
 '2.8519',
 '2.8519',
 '2.8519',
 '2.8519',
 '2.8519',
 '2.8519',
 '2.8519',
 '2.8519',
 '2.8519',
 '2.8519',
 '2.8519',
 '2.8197',
 '2.8197',
 '2.8197',
 '2.8197',
 '2.8197',
 '2.8197',
 '2.8197',
 '2.8197',
 '2.8197',
 '2.8197',
 '2.8197',
 '2.8197',
 '2.8197',
 '2.8197',
 '2.8197',
 '2.8197',
 '2.8197',
 '2.8197',
 '2.8197',
 '2.8197',
 '2.8197',
 '2.8197',
 '2.8197',
 '2.8197',
 '2.8197',
 '2.8197',
 '2.8197',
 '2.8197',
 '2.8197',
 '2.8197',
 '2.8197',
 '2.8197',
 '2.8197',
 '2.8197',
 '2.8197',
 '2.8197',
 '2.8197',
 '2.8197',
 '2.8197',
 '2.8197',
 '2.8197',

In [ ]:
sc_22 = open('/content/drive/My Drive/Datasets/EBT/sc_22.txt', 'r')
sc_22 = sc_22.read()

In [ ]:
s_22 = []
j = re.split("([A-Z][^A-Z]*)", sc_22)
# convert list to string

j = ' '.join(map(str, j))
if not j.lower() in other_words:
                  j= strip_non_alphanum(j)
                  j= strip_numeric(j)
                  j= strip_multiple_whitespaces(j)

                  sc_22 = j.lower().split()

In [ ]:
#similarity between rq_3 and sc_12
rq_3 = ['', 'registration', 'subscriber', 'register', 'control', 'subscriber', 'manager', '', 'user', 'establish', 'traces', 'requirements', 'types', 'artifacts', 'establishing', 'subscription', 'artifact', 'relevant', 'requirement', '', 'artifact', 'placed', 'control', 'subscriber', 'manager', '', 'user', 'able', 'delete', 'subscriptions', ' ']


similarity = word_vectors.wmdistance(rq_3, sc_12)
print("{:.4f}".format(similarity))

In [ ]:
#similarity between rq_4 and sc_12
rq_4 = ['', 'subscriber', 'manager', 'register', 'eventserver', 'receive', 'relevant', 'event', 'messages', ' ']
similarity = word_vectors.wmdistance(rq_4, sc_12)
print("{:.4f}".format(similarity))

In [ ]:
#similarity between rq_1 and sc_12
rq_1 = ['', 'non requirement', 'artifacts', 'managed', 'rd', 'party', 'tools', 'rational', 'rose', 'clear', 'case', '', 'registered', 'subscribers', 'allowed', 'establish', 'traces', ' ']
similarity = word_vectors.wmdistance(rq_1, sc_12)
print("{:.4f}".format(similarity))

In [ ]:
#similarity between rq_7 and sc_22
rq_7 = ['', 'subscriber', 'manager', 'receive', 'event', 'notifications', 'behalf', 'artifacts', 'manages', ' ']
similarity = word_vectors.wmdistance(rq_7, sc_22)
print("{:.4f}".format(similarity))

In [ ]:
print(list(enumerate(a)))

[(0, ['', 'requirements', 'managed', 'rd', 'party', 'requirements', 'management', 'tool', 'doors', ' ']), (1, ['', 'non requirement', 'artifacts', 'managed', 'rd', 'party', 'tools', 'rational', 'rose', 'clear', 'case', '', 'registered', 'subscribers', 'allowed', 'establish', 'traces', ' ']), (2, ['', 'user', 'register', 'subscriber', ' ']), (3, ['', 'registration', 'subscriber', 'register', 'control', 'subscriber', 'manager', '', 'user', 'establish', 'traces', 'requirements', 'types', 'artifacts', 'establishing', 'subscription', 'artifact', 'relevant', 'requirement', '', 'artifact', 'placed', 'control', 'subscriber', 'manager', '', 'user', 'able', 'delete', 'subscriptions', ' ']), (4, ['', 'subscriber', 'manager', 'register', 'eventserver', 'receive', 'relevant', 'event', 'messages', ' ']), (5, ['', 'subscriber', 'manager', 'online', ' ', 'push', 'model', 'send', 'event', 'notifications', 'real', 'time', ' ']), (6, ['', 'subscriber', 'manager', 'comes', 'line', ' ', 'implement', 'pull'

In [ ]:
#similarity between rq_12 and sc_22
rq_12 = ['', 'subscriber', 'manager', 'immediately', 'process', 'speculative', 'events', ' ']
similarity = word_vectors.wmdistance(rq_12, sc_22)
print("{:.4f}".format(similarity))

In [ ]:
#similarity between rq_22 and sc_22
rq_22 = ['', 'event', 'types', 'include', 'merging', 'requirements', ' ']
similarity = word_vectors.wmdistance(rq_22, sc_22)
print("{:.4f}".format(similarity))

In [ ]:
#similarity between rq_3 and sc_22
similarity = word_vectors.wmdistance(rq_3, sc_22)
print("{:.4f}".format(similarity))

#abc implement

In [ ]:
#import Hive
import sys
sys.path.append('/content/drive/My Drive/Colab Notebooks/Finals/EBT/Hive')

In [ ]:
try:
    import numpy as np
except:
    raise ImportError("Numpy module not installed.")
import Hive
import Utilities
import math
import random
import matplotlib.pyplot as plt
import csv
import re
import time
from collections import Counter

In [ ]:
def cosine_similarity(vector1, vector2):
    dot_product = sum(p*q for p,q in zip(vector1, vector2))
    magnitude = math.sqrt(sum([val**2 for val in vector1])) * math.sqrt(sum([val**2 for val in vector2]))
    if not magnitude:
        return 0
    return dot_product/magnitude

In [ ]:
def inverse_document_frequencies(tokenized_documents):
    idf_values = {}
    all_tokens_set = set([item for sublist in tokenized_documents for item in sublist])
    for tkn in all_tokens_set:
        contains_token = map(lambda doc: tkn in doc, tokenized_documents)
        idf_values[tkn] = 1 + math.log(len(tokenized_documents)/(sum(contains_token)))
    return idf_values

In [ ]:
def sublinear_term_frequency(term, tokenized_document):
    count = tokenized_document.count(term)
    if count == 0:
        return 0
    return 1 + math.log(count)

In [ ]:
#testing
# tokenize = lambda doc: doc.lower().split(" ")
def tfidf(tokenized_documents):
    # tokenized_documents = [tokenize(d) for d in documents]
    idf = inverse_document_frequencies(tokenized_documents)
    tfidf_documents = []
    for document in tokenized_documents:
        doc_tfidf = []
        for term in idf.keys():
            tf = sublinear_term_frequency(term, document)
            doc_tfidf.append(tf * idf[term])
        tfidf_documents.append(doc_tfidf)
    return tfidf_documents

In [ ]:
# from collections import Counter
# Counter(str(a))

In [ ]:
l1 = (scSgModel.wv)

In [ ]:
l1

In [ ]:
l2 = (rqSgModel.wv)

In [ ]:
l2 = []
for i in rqSgModel.wv.vocab:
  j = rqSgModel.wv[{i}]
  print(j)
  l2.extend(j)

In [ ]:
l1 = []
for i in scSgModel.wv.vocab:
  j = scSgModel.wv[{i}]
  print(j)
  l1.extend(j)

In [ ]:
l2

[array([-0.44717985], dtype=float32),
 array([0.30709922], dtype=float32),
 array([-0.35021704], dtype=float32),
 array([0.17677769], dtype=float32),
 array([-0.1867339], dtype=float32),
 array([0.13917547], dtype=float32),
 array([-0.02063596], dtype=float32),
 array([0.12248116], dtype=float32),
 array([0.11091715], dtype=float32),
 array([0.20422362], dtype=float32),
 array([-0.45508504], dtype=float32),
 array([-0.3554611], dtype=float32),
 array([0.387066], dtype=float32),
 array([0.30394354], dtype=float32),
 array([-0.45229942], dtype=float32),
 array([0.02136876], dtype=float32),
 array([-0.4478496], dtype=float32),
 array([0.06987878], dtype=float32),
 array([-0.46202108], dtype=float32),
 array([-0.08711384], dtype=float32),
 array([0.14846797], dtype=float32),
 array([0.07258537], dtype=float32),
 array([0.1559646], dtype=float32),
 array([-0.45761454], dtype=float32),
 array([-0.3875663], dtype=float32),
 array([0.38923743], dtype=float32),
 array([-0.48692676], dtype=float

In [ ]:
t1 = [scSgModel.wv['event']]

In [ ]:
t2 = [rqSgModel.wv['event']]

In [ ]:
cosine_similarity(t1,t2)

array([-1.0000001], dtype=float32)

In [ ]:
t1

[array([1.2455388], dtype=float32)]

In [ ]:
t2

[array([-0.15451193], dtype=float32)]

In [ ]:
b = []
b.extend(t1)
b.extend(t2)

In [ ]:
list(enumerate(b, 100))

In [ ]:
a = []
a.append(t1)
a.append(t2)

In [ ]:
list(enumerate(a, 100))

In [ ]:
# changing index and printing separately 

for count,ele in enumerate(b,100): 
  j = count+1
  for count2, ele2 in enumerate(b, 100):
     if(count2==j):
        c = cosine_similarity(ele, ele2) 
        # print(ele, ele2)
        print(c) 

-0.006958872522781549


In [ ]:
# changing index and printing separately 
for count,ele in enumerate(l2,100): 
    print(count,ele) 

In [ ]:
all = []
all.extend(l2)
all.extend(l1)

In [ ]:
len(all)

485

In [ ]:
for count,ele in enumerate(all,100): 
  print(count, ele)

In [ ]:
# changing index and printing separately 
for count,ele in enumerate(all,100): 
  j = count+1
  for j, ele2 in enumerate(all,100):

    c = cosine_similarity(ele, ele2) 
    # print(c) 


In [ ]:

# #first implementation
# tfidf_representation = tfidf(all_documents)
def docu (uno, dos, intervale):
   our_tfidf_comparisons = []
   auxilio =0
   for count_0, doc_0 in enumerate(all):
       #print ("HL", count_0, "TERMINE")
       for count_1, doc_1 in enumerate(all):
           if(count_0==uno and count_1==dos+intervale):
               our_tfidf_comparisons.append((cosine_similarity(doc_0, doc_1), count_0, count_1)) 
               auxilio=cosine_similarity(doc_0, doc_1) 
              #  print ("AUXILIO", auxilio)
               return auxilio

In [ ]:
def evaluator(vector):

    value=0.0
    valuex = 0.0
    #val = 0
    vector = np.array(vector)
    # print ("vector", vector)
    #return 10 * vector.size + sum(vector*vector - 10 * np.cos(2 * np.pi * vector))
    total = (len(vector)//2)
    # print ("total", total)
    for i in range (0,total):
        # print("------------------------------------------------------")
        # print ("i", i)
        # print ("AUXXX", len(aux))
        # print ("total", total)
        # print ("len all_doc", len(all_documents))
        # print ("vector text alllllllllllllllllllllll", all_documents)
        # print ("vector1", vector[i])
        # print ("vector text", all_documents[vector[i]])
        # print ("vector2", vector[total+i])
        # print ("vector text", all_documents[len(aux)+vector[total+i]])
        #-----------
        value =  docu(vector[i],vector[total+i],(len(l2))) #........................................................................................
        # print ("value funtion 1mnjljl", value)
        
        #EBT THESHOLD
        if value != None and value >= 0.1:
            value = 1+ value
            valuex = valuex + value
        
        #Albergate THESHOLD
        #if value >= 0.1:
        #    value = 1+ value
        #else:
        #    value = 0.0
        #print ("value funtion 1", valuex)
        # valuex = valuex + value
        #print ("value funtion 1", valuex)
        value = 0.0
        #-----------
    #print ("----------------------------------------value funtion 1", valuex)
        #val = val+ (vector[i]+vector[total+i])
    #print("TERMINE----------------------------------------------------------------")
    return valuex



In [ ]:
def run():

    # creates model
    #ndim = int (300) #Albergate
    #ndim = int(800) #eTours
    ndim = int(500) #EBT
    model = Hive.BeeHive(
                         lower = [0]*ndim  ,
                         upper = [31]*ndim  , #EBT
                         #upper = [15]*ndim  , #Albergate
                         #upper = [57]*ndim  , # eTour
                         fun       = evaluator ,
                         #numb_bees =  200       ,  #Albergate
                         #max_itrs  =  200       ,) #Albergate
                         
                         #numb_bees =  200       ,  #EBT
                         #max_itrs  =  200       ,) #EBT
                         
                         numb_bees =  50      , #eTour
                         max_itrs  = 50       ,) #eTour

    # runs model
    
    start_time = time.clock()
    cost = model.run()

    # plots convergence
    Utilities.ConvergencePlot(cost)
    B= []
    C=[]
    # prints out best solution
    print("BEEEEEEEEEEEEEEEST", model.new)
    print("Best solution ABC: {0}".format(model.best))
    #for i in range (0,400):
    for i in range (0,250):
    #for i in range (0,150):
        #print ("soy i",i)
        #print ("SOYYYYY", model.new[i])
        B.append(model.new[i])
    #for i in range (401,801):
    for i in range (251,501):
    #for i in range (151,301):
        C.append(model.new[i])

    print ("soy b", B)
    print ("soy b", C)
    total =0
    verdad =0
    local = 0
    count = 0

    #for i in range (0,400-1):
    for i in range (0,250-1):
    #for i in range (0,150-1):
        #for j in range (i+1,400):
        for j in range (i+1,250):
        #for j in range (i+1,150):
            if ((B[i] == B[j]) and (C[i]==C[j] )):
                B[j] = " "
                C[j] = " "           
                local = local+1
                verdad = 1
        if (verdad== 1):
            total = total+local
            verdad = 0
            local = 0
    print ("TOTAL", total)  
    #for i in range (0,400):
    for i in range (0,250):
    #for i in range (0,150):
        if (B[i] != " " ):
            count = count +1; 
            print ("Pair,", count, " REQ", B[i], ", SCC",  C[i])  

    print (time.clock() - start_time, "seconds")

if __name__ == "__main__":
    run()



TypeError: ignored